//Skapa en admin användare här
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "id": "User",
  "lastName": "Usersson",
  "email": "user@user.se",
  "password": "user",
  "isAdmin": false
}

###

//Logga in här
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "admin@admin.se",
  "password": "admin"
}

###